"""Helpers for the 1.5B terminal-only E1 scale protocol.

These helpers are not imported by the frozen M8b 318-count runtime gate.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping, Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
LOCK_PATH = REPOSITORY_ROOT / "configs" / "e1_scale.json"
TRAIN_YAML = REPOSITORY_ROOT / "examples" / "agemem_hotpotqa" / "agemem_e1_scale.yaml"
EVAL_YAML = (
    REPOSITORY_ROOT / "examples" / "agemem_hotpotqa" / "agemem_e1_scale_eval.yaml"
)

_WORKFLOW_ARGS = """        reward_profile: terminal_only
        terminal_reward_metric: hotpotqa_official
        milestone_reward_enabled: false
        auxiliary_provider:
          schema_version: agemem.auxiliary_provider.v1
          provider: dashscope
          base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
          embedding_model: text-embedding-v4
          embedding_dimensions: 256
          chat_model: qwen-max
          usage_tracking: true
        auto_summary_threshold: 0.8
        max_tool_rounds_per_turn: 4
        max_context_tokens: 4096
        stage2_distractor_messages: 1
        stage2_distractor_source: fixed
        stage1_max_rounds: 2
        stage2_max_rounds: 2
        stage3_max_rounds: 2
        tool_trace_enabled: true
        tool_trace_console: false
        tool_trace_max_string_chars: 8192
        tool_trace_ray_timeout_seconds: 5.0"""


def load_lock(path: Path | None = None) -> dict[str, Any]:
    target = path or LOCK_PATH
    return json.loads(target.read_text(encoding="utf-8"))


def selection_is_complete(lock: Mapping[str, Any]) -> bool:
    rows = lock.get("fixed_train_rows")
    train_size = int(lock["train_size"])
    prefix = list(lock["source_train_prefix_ids"])
    if not isinstance(rows, list) or len(rows) != train_size:
        return False
    ids = [str(row["hotpot_id"]) for row in rows]
    if ids[: len(prefix)] != prefix:
        return False
    if len(set(ids)) != train_size:
        return False
    held_out = set(lock["held_out_row_ids"])
    return held_out.isdisjoint(ids)


def _yaml_id_block(row_ids: Sequence[str]) -> str:
    return "\n".join(f"      - {row_id}" for row_id in row_ids)


def _yaml_index_block(rows: Sequence[Mapping[str, Any]]) -> str:
    return "[" + ", ".join(str(int(row["source_index"])) for row in rows) + "]"


def render_train_yaml(lock: Mapping[str, Any]) -> str:
    if not selection_is_complete(lock):
        raise ValueError("E1 scale lock does not yet contain 24 frozen train rows")
    rows = list(lock["fixed_train_rows"])
    job = lock["job_name"]
    return f"""# 1.5B terminal-only E1 scale. No format nudge. Not the frozen dry-run.
# Generated by scripts/agemem_e1_scale_select.py; do not edit row lists by hand.
project: "Trinity-RFT-AgeMem-M8"
name: "{job}"
mode: both
checkpoint_root_dir: ${{oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}}
continue_from_checkpoint: false

algorithm:
  algorithm_type: multi_step_grpo
  advantage_fn: step_wise_grpo
  repeat_times: 2

model:
  model_path: ${{oc.env:TRINITY_MODEL_PATH,/root/autodl-tmp/models/Qwen2.5-1.5B-Instruct}}
  max_model_len: 4608
  max_prompt_tokens: 4096
  max_response_tokens: 512
  lora_configs:
  - name: lora
    lora_rank: 16
    lora_alpha: 16
    path: null

cluster:
  node_num: 1
  gpu_per_node: 2

buffer:
  total_epochs: {int(lock["buffer_total_epochs"])}
  total_steps: {int(lock["buffer_total_steps"])}
  batch_size: {int(lock["batch_size"])}
  train_batch_size: {int(lock["train_batch_size"])}
  explorer_input:
    taskset:
      name: hotpotqa_e1_train_scale
      storage_type: file
      path: ${{oc.env:HOTPOTQA_PATH,/root/autodl-tmp/data/hotpot_qa/fullwiki}}
      split: train
      row_indices: {_yaml_index_block(rows)}
      row_id_key: id
      expected_row_ids:
{_yaml_id_block([str(row["hotpot_id"]) for row in rows])}
      expected_dataset_fingerprint: {lock["expected_dataset_fingerprint"]}
      format:
        prompt_key: question
        response_key: answer
      rollout_args:
        temperature: 0.6
        max_tokens: 512
      workflow_args:
{_WORKFLOW_ARGS}
    eval_tasksets: []
    default_workflow_type: AgeMem_hotpot_workflow_training
  trainer_input:
    experience_buffer:
      name: {job}_buffer
      storage_type: queue
      path: null

explorer:
  eval_on_startup: false
  eval_interval: 8
  runner_per_model: 2
  max_repeat_times_per_runner: 2
  max_timeout: 1800
  rollout_model:
    engine_num: 1
    tensor_parallel_size: 1
    enable_prefix_caching: true
    enforce_eager: true
    enable_history: true
    dtype: bfloat16
    seed: {int(lock["seed"])}
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
    enable_thinking: false

log:
  level: INFO

synchronizer:
  sync_method: checkpoint
  sync_interval: 1
  sync_timeout: 1800

trainer:
  trainer_type: verl
  total_steps: {int(lock["trainer_total_steps"])}
  save_interval: 8
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: true
        enable_gradient_checkpointing: true
      actor:
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 4608
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 0.000001
      ref:
        log_prob_use_dynamic_bsz: ${{trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}}
        log_prob_max_token_len_per_gpu: ${{trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}}
        ulysses_sequence_parallel_size: 1
"""


def render_eval_yaml(lock: Mapping[str, Any]) -> str:
    if not selection_is_complete(lock):
        raise ValueError("E1 scale lock does not yet contain 24 frozen train rows")
    train_rows = list(lock["fixed_train_rows"])
    eval_rows = list(lock["held_out_rows"])
    job = lock["job_name"]
    return f"""# New-process held-out eval of the 1.5B E1 scale job. No optimizer update.
project: "Trinity-RFT-AgeMem-M8"
name: "{job}"
mode: bench
checkpoint_root_dir: ${{oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}}
continue_from_checkpoint: true

algorithm:
  algorithm_type: multi_step_grpo
  advantage_fn: step_wise_grpo
  repeat_times: 2

model:
  model_path: ${{oc.env:TRINITY_MODEL_PATH,/root/autodl-tmp/models/Qwen2.5-1.5B-Instruct}}
  max_model_len: 4608
  max_prompt_tokens: 4096
  max_response_tokens: 512
  lora_configs:
  - name: lora
    lora_rank: 16
    lora_alpha: 16
    path: ${{oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}}/Trinity-RFT-AgeMem-M8/{job}/dummy_lora

cluster:
  node_num: 1
  gpu_per_node: 2

buffer:
  total_epochs: 1
  total_steps: 3
  batch_size: 2
  train_batch_size: 4
  explorer_input:
    taskset:
      name: hotpotqa_e1_train_scale
      storage_type: file
      path: ${{oc.env:HOTPOTQA_PATH,/root/autodl-tmp/data/hotpot_qa/fullwiki}}
      split: train
      row_indices: {_yaml_index_block(train_rows)}
      row_id_key: id
      expected_row_ids:
{_yaml_id_block([str(row["hotpot_id"]) for row in train_rows])}
      expected_dataset_fingerprint: {lock["expected_dataset_fingerprint"]}
      format:
        prompt_key: question
        response_key: answer
      rollout_args:
        temperature: 0.0
        max_tokens: 512
      workflow_args:
{_WORKFLOW_ARGS}
    eval_tasksets:
    - name: hotpotqa_m5_heldout_smoke
      storage_type: file
      path: ${{oc.env:HOTPOTQA_PATH,/root/autodl-tmp/data/hotpot_qa/fullwiki}}
      split: validation
      repeat_times: 2
      row_indices: {_yaml_index_block(eval_rows)}
      row_id_key: id
      expected_row_ids:
{_yaml_id_block([str(row["hotpot_id"]) for row in eval_rows])}
      expected_dataset_fingerprint: {lock["eval_dataset_fingerprint"]}
      format:
        prompt_key: question
        response_key: answer
      rollout_args:
        temperature: 0.0
        max_tokens: 512
      workflow_args:
{_WORKFLOW_ARGS}
    default_workflow_type: AgeMem_hotpot_workflow_training
    default_eval_workflow_type: AgeMem_hotpot_workflow_training
  trainer_input:
    experience_buffer:
      name: {job}_eval_buffer
      storage_type: queue
      path: null

explorer:
  eval_on_startup: false
  bench_on_latest_checkpoint: true
  eval_interval: 1
  runner_per_model: 2
  max_repeat_times_per_runner: 2
  max_timeout: 1800
  rollout_model:
    engine_num: 1
    tensor_parallel_size: 1
    enable_prefix_caching: true
    enforce_eager: true
    enable_history: true
    dtype: bfloat16
    seed: {int(lock["seed"])}
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
    enable_thinking: false

log:
  level: INFO

synchronizer:
  sync_method: checkpoint
  sync_interval: 1
  sync_timeout: 1800

trainer:
  trainer_type: verl
  total_steps: 1
  save_interval: 1
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: true
        enable_gradient_checkpointing: true
      actor:
        use_dynamic_bsz: true
        ppo_max_token_len_per_gpu: 4608
        ulysses_sequence_parallel_size: 1
        optim:
          lr: 0.000001
      ref:
        log_prob_use_dynamic_bsz: ${{trainer.trainer_config.actor_rollout_ref.actor.use_dynamic_bsz}}
        log_prob_max_token_len_per_gpu: ${{trainer.trainer_config.actor_rollout_ref.actor.ppo_max_token_len_per_gpu}}
        ulysses_sequence_parallel_size: 1
"""


def write_generated_yaml(lock: Mapping[str, Any]) -> None:
    TRAIN_YAML.write_text(render_train_yaml(lock), encoding="utf-8", newline="\n")
    EVAL_YAML.write_text(render_eval_yaml(lock), encoding="utf-8", newline="\n")
