"""Deterministic HotpotQA-style toy memory environment for M3."""

from .dataset import ToyTaskDataset, default_task_path
from .environment import HotpotQAToyEnvironment, ToyEnvironmentPool
from .models import (
    EpisodeSnapshot,
    EpisodeStepResult,
    MemoryEpisode,
    OracleLabels,
    StageInput,
    ToyAction,
    ToyFact,
    ToyMemoryTask,
)
from .policies import ErrorMemoryPolicy, GoldMemoryPolicy, ToyPolicy
from .runner import EpisodeRunResult, ToyEpisodeRunner
from .shortcut_benchmark import (
    AntiShortcutBenchmarkReport,
    ShortcutGate,
    Stage1ShortcutMetrics,
    anti_shortcut_markdown,
    run_anti_shortcut_benchmark,
    shortcut_report_digest,
    write_anti_shortcut_report,
)
from .storage_baselines import (
    MemoryBudgetAuditEvent,
    MemoryBudgetExceeded,
    MemoryBudgetReport,
    OracleSafeStorePolicy,
    PublicStage1Fact,
    PublicStage1Input,
    Stage1StorageBenchmark,
    Stage1StorageDecision,
    Stage1StoragePolicy,
    Stage1StorageRunResult,
    StoreAllPolicy,
    StoreNonePolicy,
    TokenBudgetMemoryStore,
    count_ltm_tokens,
    ordered_stage1_facts,
)
from .stage2_challenge import (
    AlwaysClearPolicy,
    AlwaysKeepPolicy,
    OpaqueIdControlPolicy,
    OracleSafeCompressPolicy,
    PublicStage2Input,
    Stage2BenchmarkReport,
    Stage2ChallengeCase,
    Stage2ChallengeDataset,
    Stage2CompressionDecision,
    default_stage2_challenge_path,
    evaluate_stage2_decision,
    run_stage2_challenge_benchmark,
    stage2_report_digest,
)

__all__ = [
    "AntiShortcutBenchmarkReport",
    "EpisodeRunResult",
    "EpisodeSnapshot",
    "EpisodeStepResult",
    "ErrorMemoryPolicy",
    "GoldMemoryPolicy",
    "HotpotQAToyEnvironment",
    "MemoryBudgetAuditEvent",
    "MemoryBudgetExceeded",
    "MemoryBudgetReport",
    "MemoryEpisode",
    "AlwaysClearPolicy",
    "AlwaysKeepPolicy",
    "OpaqueIdControlPolicy",
    "OracleSafeCompressPolicy",
    "OracleSafeStorePolicy",
    "PublicStage1Fact",
    "PublicStage1Input",
    "PublicStage2Input",
    "OracleLabels",
    "StageInput",
    "Stage1StorageBenchmark",
    "Stage1StorageDecision",
    "Stage1StoragePolicy",
    "Stage1StorageRunResult",
    "Stage1ShortcutMetrics",
    "Stage2BenchmarkReport",
    "Stage2ChallengeCase",
    "Stage2ChallengeDataset",
    "Stage2CompressionDecision",
    "ToyAction",
    "ToyEnvironmentPool",
    "ToyEpisodeRunner",
    "ToyFact",
    "ToyMemoryTask",
    "ToyPolicy",
    "ToyTaskDataset",
    "StoreAllPolicy",
    "StoreNonePolicy",
    "TokenBudgetMemoryStore",
    "ShortcutGate",
    "anti_shortcut_markdown",
    "count_ltm_tokens",
    "ordered_stage1_facts",
    "default_task_path",
    "default_stage2_challenge_path",
    "evaluate_stage2_decision",
    "run_stage2_challenge_benchmark",
    "run_anti_shortcut_benchmark",
    "shortcut_report_digest",
    "stage2_report_digest",
    "write_anti_shortcut_report",
]
